


# [patch."https://github.com/paradigmxyz/reth.git"]
# reth-node-api = { git = "file:///Users/rg/Projects/xyz.lattice/reth", branch = "main" }
# reth-node-optimism = { git = "file:///Users/rg/Projects/xyz.lattice/reth", branch = "main" }
# reth-primitives = { git = "file:///Users/rg/Projects/xyz.lattice/reth", branch = "main" }
# reth-rpc = { git = "file:///Users/rg/Projects/xyz.lattice/reth", branch = "main" }
# reth-rpc-api = { git = "file:///Users/rg/Projects/xyz.lattice/reth", branch = "main" }
# reth-rpc-types = { git = "file:///Users/rg/Projects/xyz.lattice/reth", branch = "main" }

# [patch."https://github.com/alloy-rs/alloy"]
